@startuml
class ExtensionFilter <<struct>> {
    + Name : string
    + ExtensionFilter(filterName:string, filterExtensions:string[])
}
class StandaloneFileBrowser {
    {static} StandaloneFileBrowser()
    + {static} OpenFilePanel(title:string, directory:string, extension:string, multiselect:bool) : string[]
    + {static} OpenFilePanel(title:string, directory:string, extensions:ExtensionFilter[], multiselect:bool) : string[]
    + {static} OpenFilePanelAsync(title:string, directory:string, extension:string, multiselect:bool, cb:Action<string[]>) : void
    + {static} OpenFilePanelAsync(title:string, directory:string, extensions:ExtensionFilter[], multiselect:bool, cb:Action<string[]>) : void
    + {static} OpenFolderPanel(title:string, directory:string, multiselect:bool) : string[]
    + {static} OpenFolderPanelAsync(title:string, directory:string, multiselect:bool, cb:Action<string[]>) : void
    + {static} SaveFilePanel(title:string, directory:string, defaultName:string, extension:string) : string
    + {static} SaveFilePanel(title:string, directory:string, defaultName:string, extensions:ExtensionFilter[]) : string
    + {static} SaveFilePanelAsync(title:string, directory:string, defaultName:string, extension:string, cb:Action<string>) : void
    + {static} SaveFilePanelAsync(title:string, directory:string, defaultName:string, extensions:ExtensionFilter[], cb:Action<string>) : void
}
@enduml
