/*using UnityEngine;
using UnityEditor;

// Completely generated by ChatGPT

[CustomEditor(typeof(GameObject))]
public class GameObjectScreenshot : Editor
{
    public override void OnInspectorGUI()
    {
        base.OnInspectorGUI();

        if (GUILayout.Button("Capture Screenshot"))
        {
            var go = target as GameObject;
            var renderer = go.GetComponentInChildren<Renderer>();

            if (renderer == null)
            {
                Debug.LogError("GameObject does not have a Renderer component.");
                return;
            }

            var texture = new Texture2D(Screen.width, Screen.height, TextureFormat.RGB24, false);
            var oldTargetTexture = renderer.sharedMaterial.mainTexture;
            var oldRenderTarget = RenderTexture.active;

            renderer.sharedMaterial.mainTexture = texture;

            RenderTexture renderTexture = new RenderTexture(Screen.width, Screen.height, 24);
            RenderTexture.active = renderTexture;
            Camera.main.targetTexture = renderTexture;

            Camera.main.Render();
            texture.ReadPixels(new Rect(0, 0, Screen.width, Screen.height), 0, 0);
            texture.Apply();

            var filename = Application.dataPath + "/Screenshots/" + go.name + ".png";
            System.IO.File.WriteAllBytes(filename, texture.EncodeToPNG());

            renderer.sharedMaterial.mainTexture = oldTargetTexture;
            RenderTexture.active = oldRenderTarget;
            Camera.main.targetTexture = null;

            Debug.Log("Screenshot saved to: " + filename);
        }
    }
}*/