@startuml
class Vector3SerializationSurrogate {
    + GetObjectData(obj:object, info:SerializationInfo, context:StreamingContext) : void
    + SetObjectData(obj:object, info:SerializationInfo, context:StreamingContext, selector:ISurrogateSelector) : object
}
ISerializationSurrogate <|-- Vector3SerializationSurrogate
@enduml
